dns_forwarders:
  - 8.8.8.8

rev_domain: 42.168.192.in-addr.arpa

hostname: adattiva
domain: adattiva.xyz
startup_name: adattiva

reverse_domain:
 - reverse: 42.168.192.in-addr.arpa.

dns_record:
 - name: vm1
   type: A
   ipaddress: 192.168.42.20
 - name: vm2
   type: A
   ipaddress: 192.168.42.40
 - name: backup
   type: A
   ipaddress: 192.168.42.156
    
mysql_host: vm2
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64356436626331636366613638623631313962656537343336616164646562353337396130343732
          6433303131316331613234363865626230393438633135380a366135376531383866663536646564
          34356639356164653734663837363233383035383832613538383239626333623164353261303264
          3833626661366630340a613431623439663037653432643632333730383265373565613237663231
          37656662383330646637633131303139343161383430336530336534376534636665

mysql_exporter_user: exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30313965336365303234653130653163343639323261346333343136613236373765393134643135
          6335316633633561643232366163303332636334353831620a623066383034356465326562313162
          65306166363334366237646662396663646638386132666462613364356334656136313764303761
          6161333130636237300a656533633733656335363835336432343165333039326237363764316162
          64383864373737336232356335626432616637633938653836393838336364663734

mysql_database_backup: backup
mysql_password_backup: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66643033653339333234316563313230343935633463363665663630613239643465643833616632
          3830303435346437393266363330396163353839333836640a646231626133396231626666346631
          65326236363833623838316462363437313333333565306235336337393361613564623163656333
          3134663133616363610a356161363930316565353139383439323933353065336237353464323263
          31613762306137313439393133326237643564633466393238613364336632383432
          
#ns_transfer_secret: !vault |
 #         $ANSIBLE_VAULT;1.1;AES256
  #        36393663343437653933353530653065353338616237343033363735303363616636656462396434
   #       3137373765306132353764623966313564363535653230370a626133393337363131646434633732
    #      37646364336431373832386334646530306634316364623138366662623331356361373538663433
     #     6130646232303039330a616364643965643265653466333562643635356639646266646662386535
      #    38396165663761616631646532396430336138623064626232663738353631636532

#ns_update_secret: 

#ns_transfer_secret: !vault |
#          $ANSIBLE_VAULT;1.1;AES256
#          63356166303463633162333266333339303966666162663336316631336665363431616337396165
#          3064646161653363376333373261613865613864346466630a646233316136333239386266363031
#          31313161386338363036356364613730663732666331313339303933303864623336613532386633
#          3966363739653830630a626330336534613931353439383635336337313332323165616466626264
#          61343235653364613565363162633637653331313630346638636331323132353237

#ns_update_secret: !vault |
#          $ANSIBLE_VAULT;1.1;AES256
#          36663031626631363736336566343338333235393838363735623061356661616364616231636461
#          3937393235316536336335613439346330323537323464350a656232323730633238366635316232
#          33366161633739343633323436316430646266353237386536393334376561343237333531353661
#          6235316262316139650a303766633335663563393138636630626431313661373039333534663431
#          63643635326535303830373531333437306364306632323665383532366662346131

                 
influxdb: influxdb

backup: 192.168.42.39

grafana_port: 3001
agama_port: 8001
prometheus_port: 9090
nginx_container_per_vm: 1

dns_cnames:
  - cname: ns
    real: "{{ groups['dns_server'][0] }}"
    type: CNAME
  - cname: prometheus
    real: "{{ groups['prometheus'][0] }}"
    type: CNAME
  - cname: db
    real: "{{ groups['db_servers'][0] }}"
    type: CNAME
  - cname: www
    real: "{{ groups['web_servers'][0] }}"
    type: CNAME
  - cname: grafana
    real: "{{ groups['grafana'][0] }}"
    type: CNAME
  - cname: grafana
    real: "{{ groups['grafana'][0] }}"
    type: CNAME
  - cname: haproxy-1
    real: "{{ groups['haproxy'][0] }}"
    type: CNAME
  - cname: haproxy-2
    real: "{{ groups['haproxy'][1] }}"
    type: CNAME

prometheus_jobs:
  - name: node
    targets: "{{ groups['all'] }}"
    port: 9100
  - name: bind
    targets:
      - "{{ groups['all'] }}"
    port: 9119
  - name: mysql
    targets:
      - "{{ groups['all'] }}"
    port: 9104
  - name: www
    targets:
      - "{{ groups['all'] }}"
    port: 9113
  - name: haproxy
    targets: "{{ groups['all'] }}"
    port: 9101
  - name: keepalived
    targets: "{{ groups['all'] }}"
    port: 9165
    
a_record:
  - subdomain: backup
    ip: 192.168.42.156    
