dns_forwarders:
  - 8.8.8.8

rev_domain: 42.168.192.in-addr.arpa

hostname: adattiva
domain: adattiva.xyz
startup_name: adattiva

reverse_domain:
 - reverse: 42.168.192.in-addr.arpa.

dns_record:
 - name: vm1
   type: A
   ipaddress: 192.168.42.20
 - name: vm2
   type: A
   ipaddress: 192.168.42.40
   
prometheus_jobs:
  - name: bind
    target: vm2
    port: 9119
  - name: mysql
    target: vm2
    port: 9104
  - name: mysql-ha
    target: vm1
    port: 9104
  - name: nginx
    target: vm1
    port: 9113   
    
mysql_host: vm2
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33333164616566663433653131623130386565626461326532636536316165633163396231383234
          3531376165356165616538636564666438623632346263330a623435356638656139376132656232
          30613766656539356538616134326163356235383231336365386162636431616364653038623762
          6363303565316235380a343933303330643535626230613135343430353638376436376239656566
          36623436353530616236396361396637636531613731373937636662656233376538

mysql_exporter_user: exporter
mysql_exporter_password: !vault | 
          $ANSIBLE_VAULT;1.1;AES256
          38353564383934643563616338393863386363373162666436343035643265363038396636623932
          6531363162613139396538353438663532633161393137320a396461326531313730376461303463
          63303566303932373465363562303134616138613764353562653665333865363731656264623930
          6334383462343161660a613861313037323661386335376430303965343131396336633038346562
          33343231303033363965316136333630366430656430643438313834313139323432
          
influxdb: influxdb

backup: 192.168.42.39

grafana_port: 3001
agama_port: 5001
nginx_container_per_vm: 1
