dns_forwarders:
  - 8.8.8.8

subnets:
  - 192.168.42.0/24;
  - 127.0.0.0/8;

rev_domain: 42.168.192.in-addr.arpa

hostname: adattiva
domain: adattiva.xyz

reverse_domain:
 - reverse: 42.168.192.in-addr.arpa.

dns_record:
 - name: vm1
   type: A
   ipaddress: 192.168.42.13
 - name: vm2
   type: A
   ipaddress: 192.168.42.43
   
prometheus_jobs:
  - name: bind
    target: vm2
    port: 9119
  - name: mysql
    target: vm2
    port: 9104
  - name: mysql-ha
    target: vm1
    port: 9104
  - name: nginx
    target: vm1
    port: 9113   
